language: node_js
node_js:
    - 0.12.2
env:
    - CC=clang CXX=clang++ npm_config_clang=1
addons:
    apt:
        packages:
        - libmagick++-dev
services:
    - mysql
    - redis
    - elasticsearch
